### ISSUE TITLE
French translation update (unable to do a pull request)

### ISSUE THREAD

**Issue by LileAuTresor** [duke4e/widgyTranslations#1]
Hi,
I updated the French translation but I don't know how to open a pull request (even reading the tutorial I don't understand anything...). Maybe you can get the updated file and make arrangements for the next update?

[fr-FR.zip](https://github.com/user-attachments/files/16013964/fr-FR.zip)

**Comment by LileAuTresor** [comment]
Ok… When I apply the translation in the application, certain sentences come out in English even though they were in French with the default translation... This is the case of "Sur Batterie" which is now displayed as "Not in Charge". However it is translated correctly in my file. Isn't there an inconsistency in the files to be downloaded for translation?

**Comment by duke4e** [comment]
thank you, added!
